import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headerContainer: {
    fontFamily: 'Inter_400Regular',
    width: "100%",
    height: 150,
    paddingTop: 50,
    alignItems: "center",
    backgroundColor: "#0D0D0D",
  },
  logo: {},
  textInputContainer: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: "#262626",
  },
  dataInput: {
    fontFamily: 'Inter_400Regular',
    flex: 1,
    fontSize: 16,
    color: "#808080",
    backgroundColor: "#262626",
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    height: 52,
    width: 70,
    marginTop: -28,
    marginRight: 4,
    marginLeft: 20,
  },
  button: {
    borderRadius: 5,
    backgroundColor: "#1E6F9F",
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 20,
    marginTop: -28,
  },
  countContainer: {
    width: "100%",
    backgroundColor: "#262626",
    justifyContent: "space-between",
    flexDirection: "row",
    paddingTop: 30,
    paddingBottom: 20,
    paddingRight: 20,
    paddingLeft: 20,
  },
  containerCreated: {
    flexDirection: "row",
  },
  textCreated: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    fontWeight: "bold",
    color: "#4EA8DE",
    paddingRight: 10,
  },
  textQtdecreated: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#D9D9D9",
    backgroundColor: "#333333",
    borderRadius: 10,
    width: 40,
    height: 19,
    textAlign: "center",
  },
  containerCompleted: {
    flexDirection: "row",
  },
  textCompleted: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#8284FA",
    paddingRight: 10,
  },
  textQtdeCompleted: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#D9D9D9",
    backgroundColor: "#333333",
    borderRadius: 10,
    width: 40,
    height: 19,
    textAlign: "center",
  },
  separatorContainer: {
    width: "100%",
    backgroundColor: "#262626",
  },
  separator: {
    height: 1,
    marginLeft: 22,
    marginRight: 22,
    backgroundColor: "#333333",
  },
  flatList: {
    backgroundColor: "#262626",
  },
});
